### ISSUE TITLE
Update Elternzugang 2/24

### ISSUE THREAD

**Issue by richardjubla** [jubla-ch/handbuch-jubladb-hitobito#1]
Die Verwaltung der Verwalter-Verbindung (Elternzugang) wurde überarbeitet und aus meiner sicht "intuitiver" gemacht: Sie sollte nun "direkter" sichtbar sein:

Profil-Ansicht
![image](https://github.com/jubla-ch/handbuch-jubladb-hitobito/assets/95908537/a9db1f95-0773-47f1-9c80-8fa7887224b3)

Profil mit Kindern
![image](https://github.com/jubla-ch/handbuch-jubladb-hitobito/assets/95908537/d5fbb66c-cd04-484e-81ef-7865f5e5d288)

Profil von verwaltetem Kind
![image](https://github.com/jubla-ch/handbuch-jubladb-hitobito/assets/95908537/a067827c-976c-4f33-94b0-c3d5242b6869)

Sobald ein Profil durch die Verwalter-Verbindung zum Kind oder zum Elternteil wurde, wird nur noch diese Möglichkeit angeboten: Ein Kind kann nicht Verwalter*in sein und ein Verwalter*in nicht mehr kind. Aktuell weiss ich nicht, ob das neu so gewollt ist. auf jeden fall sind unsere Anleitungen Screenshots am dem Release nicht mehr aktuell.

@patriziajubla und @chrisgwerder

**Comment by chrisgwerder** [comment]
@richardjubla:
Vielen Dank für die Info.
Sehe ich das richtig, dass dies erst für die Test-DB gilt und noch nicht für die Live-DB?

Ich würde sonst einen Branch inkl. Pull-Request machen, den man bei der Aktualisierung der Live-DB per Merge des Pull-Request live schalten kann.

In deinen Fotos sind die Eltern als Versandadresse erfasst. Findest du das auch die bessere Option? War nicht sicher ob Extern oder Versandadresse. Das Demo-Video hat aber Extern vorgeführt und so habe ich das übernommen. Die Versandadresse gefällt mir besser, da man in der Gruppen nicht noch den Reiter auf Extern umschalten muss. Die Benennung ist einfach ein wenig irreführend. 

Danke und Gruss
Christian

**Comment by richardjubla** [comment]
> Sehe ich das richtig, dass dies erst für die Test-DB gilt und noch nicht für die Live-DB?
Korrekt. Auf der Stage/Test-Umgebung ist der Zustand, der ab dem Quartalsrelease Hitobito/jubla.db 2/24 (Di, 2. April  2024) auf dem produktiven System ankommen soll.

> Ich würde sonst einen Branch inkl. Pull-Request machen, den man bei der Aktualisierung der Live-DB per Merge des Pull-Request live schalten kann.
Tönt sehr gut. Ich könnte mir aber auch vorstellen, dass die Zukunft vorweggenommen werden würde. Nicht perfekt, aus meiner Sicht aber auch möglich und vertretbar. 

> In deinen Fotos sind die Eltern als Versandadresse erfasst. Findest du das auch die bessere Option? War nicht sicher ob Extern oder Versandadresse. Das Demo-Video hat aber Extern vorgeführt und so habe ich das übernommen. Die Versandadresse gefällt mir besser, da man in der Gruppen nicht noch den Reiter auf Extern umschalten muss. Die Benennung ist einfach ein wenig irreführend.

Die **Rolle Extern** kann nur öffentliche Daten (Gruppen, Anlässe und Abos; keine anderen Personen) sehen. Diese Rolle ist nur von Personen **in der gleichen Ebene** sichtbar, nicht von Personen aus darüber liegenden Ebenen.
Die **Rolle Versandadresse** kann nur öffentliche Daten (Gruppen, Anlässe und Abos; keine anderen Personen) sehen.

Kurz: Persönlich würde ich mit Versandadresse arbeiten. 

Eine etwas ausweichende Antwort: Profile über die externe Registrierung würde ich immer zuerst mit der Rolle "Extern" versehen. Danach kann individuell je nach Grösse und Organisation der Schar gehandhabt werden: Eine Gruppe für alle Eltern mit der Rolle Versandadresse oder verschiedene "Gruppen" gleich mit den Kindern und Eltern gemischt. Wenn der Verein seine Adressen nur den zuständigen Personen sichtbar machen will, ist dies mit einzelnen Gruppen und der Rolle Extern umsetzbar.

In einer Kindergruppe haben die Mitglieder die Rolle "Kind", die dazugehörigen Eltern wären dann "getrennt" über die Auswahl "Extern" von den Kindern getrennt. 
Die Gruppenleitung dieser Kindergruppe wäre alleine für die Verwaltung der Kontakte zuständig.
